INSERT INTO WORDS (chineseCharacters, pinyin, meaning)
VALUES 
  ("爱", "ai4", "to love"),
  ("爱好", "ai4 hao4", "hobby"),
  ("八", "ba1", "eight"),
  ("爸爸", "ba4 ba", "dad"),
  ("吧", "ba", "suggestion particle"),
  ("白", "bai2", "white"),
  ("白天", "bai2 tian1", "day"),
  ("百", "bai3", "hundred"),
  ("班", "ban1", "class"),
  ("半", "ban4", "half"),
  ("半年", "ban4 nian2", "half a year"),
  ("半天", "ban4 tian1", "half a day"),
  ("帮", "bang1", "help"),
  ("帮忙", "bang1 mang2", "help"),
  ("包", "bao1", "bag"),
  ("包子", "bao1 zi", "steamed stuffed bun"),
  ("杯", "bei1", "classifier for cup"),
  ("杯子", "bei1 zi", "cup"),
  ("北", "bei3", "north"),
  ("北边", "bei3 bian1", "north side"),
  ("北京", "bei3 jing1", "capital of China"),
  ("本", "ben3", "measure word for book"),
  ("本子", "ben3 zi", "notebook"),
  ("比", "bi3", "particle used for comparison"),
  ("别", "bie2", "don't"),
  ("别的", "bie2 de", "other"),
  ("别人", "bie2 ren2", "other people"),
  ("病", "bing4", "sick/disease"),
  ("病人", "bing4 ren2", "sick person"),
  ("不大", "bu2 da4", "not big"),
  ("不对", "bu2 dui4", "not correct"),
  ("不客气", "bu2 ke4 qi4", "no worries/your welcome"),
  ("不用", "bu2 yong4", "need not"),
  ("不", "bu4", "not/no"),
  ("菜", "cai4", "dish"),
  ("茶", "cha2", "tea"),
  ("差", "cha4", "differ from/bad"),
  ("常", "chang1", "often"),
  ("常常", "chang1 chang1", "often"),
  ("唱", "chang4", "sing"),
  ("唱歌", "chang4 ge1", "sing a song"),
  ("车", "che1", "car"),
  ("车票", "che1 piao4", "ticket"),
  ("车上", "che1 shang4", "in the car"),
  ("车站", "che1 zhan4", "station/stop"),
  ("吃", "chi1", "eat"),
  ("吃饭", "chi1 fan4", "have a meal"),
  ("出", "chu1", "go or come out"),
  ("出来", "chu1 lai2", "come out"),
  ("出去", "chu1 qu4", "go out"),
  ("穿", "chuan1", "wear"),
  ("床", "chuang2", "bed"),
  ("次", "ci4", "measure word for times"),
  ("从", "cong2", "from"),
  ("错", "cuo4", "wrong"),
  ("打", "da3", "hit/take"),
  ("打车", "da3 che1", "take a car"),
  ("打电话", "da3 dian4 hua4", "take a phone call"),
  ("打开", "da3 kai1", "turn on"),
  ("打球", "da3 qiu2", "play ball"),
  ("大", "da4", "large/big"),
  ("大学", "da4 xue2", "university"),
  ("大学生", "da4 xue2 sheng1", "university student"),
  ("到", "dao4", "reach/arrive"),
  ("得到", "de2 dao4", "get"),
  ("地", "de", "like the suffix -ly in English, converts adjectives into adverbs"),
  ("的", "de", "possesive particle"),
  ("等", "deng3", "wait"),
  ("地", "di4", "ground"),
  ("地点", "di4 dian3", "specific location, address"),
  ("地方", "di4 fang", "place, region, area"),
  ("地上", "di4 shang4", "on the ground"),
  ("地图", "di4 tu2", "map"),
  ("弟弟", "di4 di", "younger brother"),
  ("第", "di4", "indicating ordinal number"),
  ("点", "dian3", "point, dot, drop, speck, o'clock"),
  ("电", "dian4", "electricity"),
  ("电话", "dian4 hua4", "phone"),
  ("电脑", "dian4 nao3", "computer"),
  ("电视", "dian4 shi4", "television"),
  ("电视机", "dian4 shi4 ji1", "television set"),
  ("电影", "dian4 ying3", "film"),
  ("电影院", "dian4 ying3", "cinema/movie theatre"),
  ("东", "dong1", "east"),
  ("东边", "dong1 bian1", "east side"),
  ("东西", "dong1 xi", "thing"),
  ("动", "dong4", "move"),
  ("动作", "dong4 zuo4", "movement"),
  ("都", "dou1", "all"),
  ("读", "du2", "read"),
  ("读书", "du2 shu1", "read a book/study"),
  ("对", "dui4", "correct"),
  ("对不起", "dui4 bu qi3", "sorry"),
  ("多", "duo1", "many"),
  ("多少", "duo1 shao", "how many"),
  ("饿", "e4", "hungry"),
  ("儿子", "er2 zi", "son"),
  ("二", "er4", "two"),
  ("饭", "fan4", "rice/meal"),
  ("饭店", "fan4 dian4", "restaurant"),
  ("房间", "fang2 jian1", "room"),
  ("房子", "fang2 zi", "house/building"),
  ("放", "fang4", "put down/lay down"),
  ("放假", "fang4 jia4", "have a holiday"),
  ("放学", "fang4 xue2", "off school"),
  ("飞", "fei1", "fly"),
  ("飞机", "fei1 ji1", "plane"),
  ("非常", "fei1 chang2", "very"),
  ("分", "fen1", "minute/point/mark"),
  ("风", "feng1", "wind"),
  ("干", "gan1", "dry"),
  ("干净", "gan1 jing4", "clean"),
  ("干", "gan4", "do"),
  ("干什么", "gan4", "what to do"),
  ("高", "gao1", "tall"),
  ("高兴", "gao1 xing4", "happy"),
  ("告诉", "gao4 su", "tell"),
  ("哥哥", "ge1 ge", "older brother"),
  ("歌", "ge1", "song"),
  ("个", "ge4", "before nouns without special measure words of their own"),
  ("给", "gei3", "give"),
  ("跟", "gen1", "with"),
  ("工人", "gong1 ren2", "workers"),
  ("工作", "gong1 zuo4", "work"),
  ("关", "guan1", "shut/close/turn off"),
  ("关上", "guan1 shang4", "shut/close/turn off"),
  ("贵", "gui4", "expensive"),
  ("国", "guo2", "country"),
  ("国家", "guo2 jia1", "country"),
  ("国外", "guo2 wai4", "abroad/overseas"),
  ("过", "guo4", "pass/review/spend/pass time"),
  ("还", "hai2", "also/still/yet"),
  ("还是", "hai2 shi4", "still"),
  ("还有", "hai2 you3", "also/in addition/there still remains"),
  ("孩子", "hai2 zi", "children"),
  ("汉语", "han4 yu3", "chinese language"),
  ("汉字", "han4 zi4", "chinese character"),
  ("好", "hao3", "good"),
  ("好吃", "hao3 chi1", "tasty"),
  ("好看", "hao3 kan4", "good looking"),
  ("好听", "hao3 ting1", "pleasant to hear"),
  ("好玩儿", "hao3 wanr2", "fun/interesting"),
  ("号", "hao4", "number/date"),
  ("喝", "he1", "drink"),
  ("和", "he2", "and"),
  ("很", "hen3", "very"),
  ("后", "hou4", "behind"),
  ("后边", "hou4 bian1", "behind/back side"),
  ("后天", "hou4 tian1", "day after tomorrow"),
  ("花", "hua1", "flower"),
  ("话", "hua4", "word/words"),
  ("坏", "huai4", "bad"),
  ("还", "huan2", "return/pay back"),
  ("回", "hui2", "go back/return"),
  ("回答", "hui2 da2", "answer/respond"),
  ("回到", "hui2 dao4", "back to"),
  ("回家", "hui2 jia1", "go home/return home"),
  ("回来", "hui2 lai2", "come back/return"),
  ("回去", "hui2 qu4", "go back/return"),
  ("会", "hui4", "can/be able to/in the future"),
  ("火车", "huo3 che1", "train"),
  ("机场", "ji1 chang3", "airport"),
  ("机票", "ji1 piao4", "plane ticket"),
  ("鸡蛋", "ji1 dan4", "egg"),
  ("几", "ji3", "several"),
  ("记", "ji4", "remember/write down"),
  ("记得", "ji4 de2", "remember"),
  ("记住", "ji4 zhu4", "remember by heart"),
  ("家", "jia1", "measure word for family or business establishments/home"),
  ("家里", "jia1 li3", "in the home"),
  ("家人", "jia1 ren2", "family members"),
  ("间", "jian1", "space in between/measure word for rooms"),
  ("见", "jian4", "see/meet"),
  ("见面", "jian4 mian4", "meet"),
  ("教", "jiao1", "teaach"),
  ("叫", "jiao4", "call/be called"),
  ("教学楼", "jiao1 xue2 lou2", "teaching building"),
  ("姐姐", "jie3 jie", "older sister"),
  ("介绍", "jie4 shao4", "introduce/present"),
  ("今年", "jin1 nian2", "this year"),
  ("今天", "jin1 tian1", "today"),
  ("进", "jin4", "enter"),
  ("进来", "jin4 lai2", "come in"),
  ("进去", "jin4 qu4", "go in"),
  ("九", "jiu3", "nine"),
  ("就", "jiu4", "as soon as/right away/then"),
  ("觉得", "jue2 de", "think"),
  ("开", "kai1", "open"),
  ("开车", "kai1 che1", "drive/drive a car"),
  ("开会", "kai1 hui4", "have a meeting"),
  ("开玩笑", "kai1 wan2 xiao4", "crack/play a joke/pull one's leg"),
  ("看", "kan4", "see/look"),
  ("看病", "kan4 bing4", "see a doctor"),
  ("看到", "kan4 dao4", "see and perceive"),
  ("看见", "kan4 jian", "catch sight of"),
  ("考", "kao3", "take a test/test/exam"),
  ("考试", "kao3 shi4", "examination"),
  ("渴", "ke3", "thirsty"),
  ("课", "ke4", "course/subject/class"),
  ("课本", "ke4 ben3", "textbook"),
  ("课文", "ke4 wen2", "text of a lesson"),
  ("口", "kou3", "mouth"),
  ("块", "kuai4", "block/lump/colloquial for gold of silver dollars/casual way of saying yuan2 the currency of China"),
  ("快", "kuai4", "fast/hurry"),
  ("来", "lai2", "come"),
  ("来到", "lai2 dao4", "come and arrive"),
  ("老", "lao3", "old"),
  ("老人", "lao3 ren2", "old person/people"),
  ("老师", "lao3 shi1", "teacher"),
  ("了", "le", "indicator of action having passed"),
  ("累", "lei4", "tired"),
  ("冷", "leng2", "cold"),
  ("里", "li3", "in"),
  ("里边", "li2 bian1", "inside"),
  ("两", "liang3", "two"),
  ("零", "ling2", "zero"),
  ("六", "liu4", "six"),
  ("楼", "lou2", "floor/storied building/storey"),
  ("楼上", "lou2 shang4", "upstairs"),
  ("楼下", "lou2 xia4", "downstairs"),
  ("路", "lu4", "road"),
  ("路口", "lu4 kou3", "intersection/crossing"),
  ("路上", "lu4 shang4", "on the road"),
  ("妈妈", "ma1 ma", "mother"),
  ("马路", "ma3 lu4", "road/street"),
  ("马上", "ma3 shang4", "at once/in the near future"),
  ("吗", "ma", "question particle"),
  ("买", "mai3", "buy"),
  ("慢", "man4", "slow"),
  ("忙", "mang2", "busy"),
  ("毛", "mao2", "a fractional unit of money in China (measure word)"),
  ("没", "mei2", "no/not have/there is not"),
  ("没关系", "mei2 guan1 xi", "no problem/don't worry about it"),
  ("没什么", "mei2 shen2 me", "it's nothing"),
  ("没事儿", "mei2 shir4", "it's okay"),
  ("没有", "mei2 you3", "not have"),
  ("妹妹", "mei4 mei", "younger sister"),
  ("门", "men2", "door"),
  ("门口", "men2 kou3", "doorway"),
  ("门票", "men2 piao4", "tickets"),
  ("们", "men", "plural for pronouns and a few animate nouns"),
  ("米饭", "mi3 fan4", "steamed rice"),
  ("面包", "mian4 bao1", "bread"),
  ("面条儿", "mian4 tiaor2", "noodles"),
  ("名字", "ming2 zi", "name"),
  ("明白", "ming2 bai", "clear/obvious/understand"),
  ("明年", "ming2 nian2", "next year"),
  ("明天", "ming2 tian1", "tomorrow"),
  ("拿", "na2", "take/hold/seize/firm grasp of/be able to do"),
  ("哪", "na3", "which"),
  ("哪里", "na3 li3", "where"),
  ("哪儿", "nar3", "where"),
  ("哪些", "na3 xie1", "which"),
  ("那", "na4", "that"),
  ("那边", "na4 bian1", "that side/over there"),
  ("那里", "na4 li3", "that place"),
  ("那儿", "nar4", "that place"),
  ("那些", "na4 xie1", "those"),
  ("奶", "nai3", "milk"),
  ("奶奶", "nai3 nai", "grandma"),
  ("男", "nan2", "man"),
  ("男孩儿", "nan2 hair2", "boy (colloquialism of Northern accent)"),
  ("男朋友", "nan2 peng2 you3", "boyfriend"),
  ("男人", "nan2 ren2", "man"),
  ("男生", "nan2 sheng1", "male student/young man"),
  ("南", "nan2", "south"),
  ("南边", "nan2 bian1", "south side"),
  ("难", "nan2", "hard/difficult"),
  ("呢", "ne", "used at the end of questions with interrogative pronouns/after a pronoun or noun phrase to form a simple interrogative sentence"),
  ("能", "neng2", "can"),
  ("你", "ni3", "you"),
  ("你们", "ni3 men", "you (plural)"),
  ("年", "nian2", "year"),
  ("您", "nin2", "you (respectful)"),
  ("牛奶", "niu2 nai3", "milk"),
  ("女", "nu3", "woman"),
  ("女儿", "nu3 er2", "woman"),
  ("女孩儿", "nu3 hair2", "girl"),
  ("女朋友", "nu3 peng2 you3", "girlfriend"),
  ("女人", "nu3 ren2", "woman"),
  ("女生", "nu3 sheng1", "female student/young woman"),
  ("旁边", "pang2 bian1", "side"),
  ("跑", "pao3", "run"),
  ("朋友", "peng2 you3", "friend"),
  ("票", "piao4", "ticket"),
  ("七", "qi1", "seven"),
  ("起", "qi3", "get up/start/rise"),
  ("起床", "qi3 chuang2", "get up at the start of the day/get up from bed"),
  ("起来", "qi3 lai2", "get up"),
  ("汽车", "qi4 che1", "car"),
  ("前", "qian2", "front"),
  ("前边", "qian2 bian1", "front side"),
  ("前天", "qian2 tian1", "the day before yesterday"),
  ("钱", "qian2", "money"),
  ("钱包", "qian2 bao1", "wallet"),
  ("请", "qing3", "please"),
  ("请假", "qing3 jia4", "ask for leave"),
  ("请进", "qing3 jin4", "please come in"),
  ("请问", "qing3 wen4", "excuse me"),
  ("请坐", "qing3 zuo4", "please have a seat"),
  ("球", "qiu2", "ball"),
  ("去", "qu4", "go"),
  ("去年", "qu4 nian2", "last year"),
  ("热", "re4", "hot"),
  ("人", "ren2", "person/people"),
  ("认识", "ren2 shi", "know"),
  ("认真", "ren2 zhen1", "earnest/conscientious/serious"),
  ("日", "ri4", "date"),
  ("日期", "ri4 qi1", "date"),
  ("肉", "rou4", "meat"),
  ("三", "san1", "three"),
  ("山", "shan1", "mountain"),
  ("商场", "shang1 chang3", "shopping mall"),
  ("商店", "shang1 dian4", "shop"),
  ("上", "shang4", "upper (as an adjective)/most recent/first/get on/go to/be engaged"),
  ("上班", "shang4 ban1", "go to work"),
  ("上边", "shang4 bian1", "above/on"),
  ("上车", "shang4 che1", "get on"),
  ("上次", "shang4 ci4", "last time"),
  ("上课", "shang4 ke4", "attend class/have class"),
  ("上网", "shang4 wang3", "surf the internet"),
  ("上午", "shang4 wu3", "morning"),
  ("上学", "shang4 xue2", "go to school"),
  ("少", "shao3", "less/few"),
  ("谁", "shei2", "who"),
  ("身上", "shen1 shang4", "on one's body/have something on one/have something with one"),
  ("身体", "shen1 ti3", "body/health"),
  ("什么", "shen2 me", "what (before a noun or by itself)/something/anything"),
  ("生病", "sheng1 bing4", "fall ill"),
  ("生气", "sheng1 qi4", "get angry"),
  ("生日", "sheng1 ri4", "birthday"),
  ("十", "shi2", "ten"),
  ("时候", "shi2 hou", "moment in time"),
  ("时间", "shi2 jian1", "period of time"),
  ("事", "shi4", "thing"),
  ("试", "shi4", "try"),
  ("是", "shi4", "is"),
  ("是不是", "shi4 bu2 shi4", "isn't it"),
  ("手", "shou3", "hand"),
  ("手机", "shou4 ji1", "phone"),
  ("书", "shu1", "book"),
  ("书包", "shu1 bao1", "school bag"),
  ("书店", "shu1 dian4", ""),
  ("树", "shu4", "tree"),
  ("水", "shui3", "water"),
  ("水果", "shui3 guo3", "fruits"),
  ("睡", "shui4", "sleep"),
  ("睡觉", "shui4 jiao4", "sleep"),
  ("说", "shou1", "speak"),
  ("说话", "shou1 hua4", "talk"),
  ("四", "si4", "four"),
  ("送", "song4", "give"),
  ("岁", "sui4", "year/age"),
  ("他", "ta1", "he"),
  ("他们", "ta1 men", "they"),
  ("她", "ta1", "she"),
  ("她们", "ta1 men", "they"),
  ("太", "tai4", "too"),
  ("天", "tian1", "day"),
  ("天气", "tian1 qi4", "weather"),
  ("听", "ting1", "hear"),
  ("听到", "ting1 dao4", "hear (emphasis on understanding)"),
  ("听见", "ting1 jian4", "hear (emphasis on simply hearing)"),
  ("听写", "ting1 xie3", "dictation"),
  ("同学", "tong2 xue2", "classmate/colleague"),
  ("图书馆", "tu2 shu1 guan3", "library"),
  ("外", "wai4", "abroad/outside"),
  ("外边", "wai4 bian1", "outside"),
  ("外国", "wai4 guo2", "foreign country"),
  ("外语", "wai4 yu3", "foreign language"),
  ("玩儿", "wanr2", "play/have fun/engage in"),
  ("晚", "wan3", "late"),
  ("晚饭", "wan3 fang4", "dinner"),
  ("晚上", "wan3 shang", "night"),
  ("网上", "wang3 shang4", "online"),
  ("网友", "wang3 you3", "online friend"),
  ("忘", "wang4", "forget"),
  ("忘记", "wang4 ji4", "forget"),
  ("问", "wen4", "ask"),
  ("我", "wo3", "I"),
  ("我们", "wo3 men", "us"),
  ("五", "wu3", "five"),
  ("午饭", "wu3 fan4", "lunch"),
  ("西", "xi1", "west"),
  ("西边", "xi1 bian1", "west side"),
  ("洗", "xi3", "wash"),
  ("洗手间", "xi3 shou3 jian1", "restroom"),
  ("喜欢", "xi3 huan", "like"),
  ("下", "xia4", "below/under/next/go down/get off"),
  ("下班", "xia4 ban1", "get off work"),
  ("下边", "xia4 bian1", "below/under"),
  ("下车", "xia4 che1", "get off"),
  ("下次", "xia4 ci4", "next time"),
  ("下课", "xia4 ke4", "finish class/get off class"),
  ("下午", "xia4 wu3", "afternoon"),
  ("下雨", "xia4 yu3", "rain"),
  ("先", "xian1", "before"),
  ("先生", "xian1 sheng", "sir"),
  ("现在", "xian4 zai4", "now"),
  ("想", "xiang3", "think"),
  ("小", "xiao3", "small"),
  ("小孩儿", "xiao3 hair2", "child/kid"),
  ("小姐", "xiao3 jie3", "Miss"),
  ("小朋友", "xiao3 peng2 you3", "children/kids"),
  ("小时", "xiao3 shi2", "hour"),
  ("小学", "xiao3 xue2", "primary school/elementary school"),
  ("小学生", "xiao3 xue2 sheng1", "elementary school student"),
  ("笑", "xiao4", "laugh"),
  ("写", "xie3", "write"),
  ("谢谢", "xie4 xie", "thanks"),
  ("新", "xin1", "new"),
  ("新年", "xin1 nian2", "New Year"),
  ("星期", "xing1 qi1", "week"),
  ("星期日", "xing1 qi1 ri4", "Sunday"),
  ("星期天", "xing1 qi1 tian1", "Sunday"),
  ("行", "xing2", "behaviour;conduct/go;walk;travel/that's okay/soon"),
  ("休息", "xiu1 xi", "rest"),
  ("学", "xue2", "learn/study"),
  ("学生", "xue2 sheng", "student"),
  ("学习", "xue2 xi2", "study"),
  ("学校", "xue2 xiao4", "school"),
  ("学院", "xue2 yuan4", "college/academy"),
  ("要", "yao4", "want"),
  ("爷爷", "ye2 ye", "grandpa"),
  ("也", "ye3", "also"),
  ("页", "ye4", "page"),
  ("一", "yi1", "one"),
  ("衣服", "yi1 fu", "clothes"),
  ("医生", "yi1 sheng1", "doctor"),
  ("医院", "yi1 yuan4", "hospital"),
  ("一半", "yi2 ban4", "half"),
  ("一会儿", "yi2 huir4", "a little while"),
  ("一块儿", "yi2 kuair4", "same place/together"),
  ("一下儿", "yi1 xiar4", "a little bit (softens a command or just asks for a little bit)"),
  ("一样", "yi2 yang4", "equally"),
  ("一边", "yi1 bian1", "one side"),
  ("一点儿", "yi1 dianr3", "a little bit"),
  ("一起", "yi1 qi3", "together"),
  ("一些", "yi1 xie1", "a number of;certain;some;a few;a little"),
  ("用", "yong4", "use"),
  ("有", "you3", "have"),
  ("有的", "you3 de", "some/part of a group/subset of things"),
  ("有名", "you3 ming2", "famous"),
  ("有时候", "you3 shi2 hou4", "sometimes"),
  ("有些", "you3 xie1", "some"),
  ("有用", "you3 yong4", "useful/available"),
  ("右", "you4", "right (side)"),
  ("右边", "you4 bian", "right side"),
  ("雨", "yu4", "rain"),
  ("元", "yuan1", "element;essential factor/unit;component/money"),
  ("远", "yuan4", "far of space and time or relationship"),
  ("月", "yue4", "month"),
  ("再", "zai4", "again"),
  ("再见", "zai4 jian4", "bye"),
  ("在", "zai4", "stay;in process of"),
  ("在家", "zai4 jia1", "at home"),
  ("早", "zao3", "early"),
  ("早饭", "zao3 fan4", "breakfast"),
  ("早上", "zao3 shang", "morning"),
  ("怎么", "zen3 me", "how"),
  ("站", "zhan4", "station"),
  ("找", "zhao3", "look for"),
  ("找到", "zhao3 dao4", "find"),
  ("这", "zhe4", "here"),
  ("这边", "zhe4 bian1", "this die"),
  ("这里", "zhe4 li3", "here"),
  ("这儿", "zher4", "here"),
  ("这些", "zhe4 xie1", "these"),
  ("着", "zhe", "in the process of"),
  ("真", "zhen1", "really"),
  ("真的", "zhen1 de", "really"),
  ("正", "zheng4", "just;exactly/straight;upright/proper"),
  ("正在", "zheng4 zai4", "in the process of/in the middle of"),
  ("知道", "zhi1 dao4", "know"),
  ("知识", "zhi1 shi", "knowledge"),
  ("中", "zhong1", "middle"),
  ("中国", "zhong1 guo2", "China"),
  ("中间", "zhong1 jian1", "among;between/on the way;in the course"),
  ("中文", "zhong1 wen2", "Chinese"),
  ("中午", "zhong1 wu3", "midday"),
  ("中学", "zhong1 xue2", "middle school"),
  ("中学生", "zhong1 xue2 sheng1", "middle school student"),
  ("重", "zhong4", "heavy"),
  ("重要", "zhong4 yao4", "important"),
  ("住", "zhu4", "live"),
  ("准备", "zhun3 bei4", "get ready/intend/plan"),
  ("桌子", "zhuo1 zi", "table"),
  ("字", "zi4", "word/character"),
  ("子", "zi", "noun suffix"),
  ("走", "zou3", "go/walk"),
  ("走路", "zou3 lu4", "walk"),
  ("最", "zui4", "most"),
  ("最好", "zui4 hao3", "best"),
  ("最后", "zui4 hou4", "last"),
  ("昨天", "zuo2 tian1", "yesterday"),
  ("左", "zuo3", "left"),
  ("左边", "zuo3 bian", "left side"),
  ("坐", "zuo4", "sit"),
  ("坐下", "zuo4 xia4", "sit down"),
  ("做", "zuo4", "do")